### PR TITLE
Use cpu arch in kubectl download url

### PR DESCRIPTION
**Pull request by debugger24**

### CODE REVIEW

**Comment by debugger24** [comment]
Is there any automated way to update Values section README.md table ?

**Comment by dlen** [comment]
Thanks for your contribution @debugger24 !

We usually use [helm-docs](https://github.com/norwoodj/helm-docs) to auto-generate the readme table based on the comments of the values.yaml

**Comment by djtecha** [comment]
I believe this will fail on most pi's btw too since the uname -m returns aarch64. I'm happy I ran into this issue though as the job kept crashing until I hardcoded it like so:

```
    KUBECTL_DOWNLOAD_CMD: "curl -LO \"https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl\""

**Comment by dlen** [comment]
Hello!

Thanks for the contribution! However, in the current state, we won't be merging it as we believe that it is enough with the KUBECTL_DOWNLOAD_CMD from values.yaml.

**Pull request closed without merging**
