### PR TITLE
feat: expose the HTTP port in the service

### PR DESCRIPTION
**Pull request by Kuruyia**
This modifies the service to also expose the HTTP service. My use case is that, in my cluster, TLS termination is handled by the ingress controller and TLS certificates are managed by cert-manager, so that the application does not have to worry about TLS at all (I think this is a very common setup).

The `service` key in the values was also updated to allow modifying the `port`, `targetPort` and `name` keys of both the HTTP and HTTPS ports.

This is a breaking change. As this is a change I would very much like to see in upstream, please tell me if something needs to be done about backwards compatibility.

### CODE REVIEW

**Comment by dlen** [comment]
Hello! 

We will be (most likely  next month) doing a release 1.0 that will include the breaking changes you suggest in this PR along some other changes.  Hope that you can wait a bit more! 

Thanks a lot for your contributions, really appreciated!

**Comment by Kuruyia** [comment]
Hi!

I have no problem waiting, I can use my fork in the meantime 😄

Thanks a lot for merging my contributions!

**Comment by alexiiiiiiiiiiiiiii** [comment]
Any news about this ? :)

**Comment by dlen** [comment]
Hello @Xhelliom! Thanks for the kind words! :heart: 

We are planning to work on the chart in a couple of weeks, our bandwidth is a bit limited so bear with us :)

**Comment by MariiAnet** [comment]
Hi!

Any news about the chart release?

**Comment by dlen** [comment]
Hello!

Yes, we have been working on it this last few days and next week it will be out as a release candidate for people to test as it contains few breaking changes.

**Pull request merged**
